# Generated by Django 3.0.1 on 2020-01-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField()),
                ('number_of_adults', models.IntegerField()),
                ('number_of_children', models.IntegerField()),
                ('arrival', models.DateField()),
                ('checkOut', models.DateField()),
                ('payment', models.CharField(choices=[('IMEPay', 'IMEPay'), ('Khalti', 'Khalti'), ('IPay', 'IPay'), ('Prabhu Pay', 'Prabhu Pay'), ('E-sewa', 'E-sewa')], default='IMEPay', max_length=20)),
                ('comment', models.TextField(null=True)),
            ],
        ),
    ]
