# Generated by Django 3.0.1 on 2020-01-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, null=True)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='book',
            name='payment',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('level', models.IntegerField()),
                ('types', models.CharField(max_length=20)),
                ('booking', models.ManyToManyField(to='WebApp.Book')),
                ('guests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Guest')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('payment', models.CharField(choices=[('IMEPay', 'IMEPay'), ('Khalti', 'Khalti'), ('IPay', 'IPay'), ('Prabhu Pay', 'Prabhu Pay'), ('E-sewa', 'E-sewa')], default='IMEPay', max_length=20)),
                ('comment', models.TextField(null=True)),
                ('guests', models.ManyToManyField(to='WebApp.Guest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.Room')),
            ],
        ),
    ]
